name: pilot_refresh
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  http: ^1.1.0
  url_launcher: ^6.2.1
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  share_plus: ^7.2.1
  pdf: ^3.10.7
  shared_preferences: ^2.2.2
  open_file: ^3.3.2
  intl: ^0.19.0
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: AbhayaLibre
      fonts:
        - asset: fonts/AbhayaLibre-Regular.ttf  
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf    

