name: pilot_refresh
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  http: ^1.1.0
  url_launcher: ^6.2.1
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  share_plus: ^7.2.1
  pdf: ^3.10.7
  shared_preferences: ^2.2.2
  open_file: ^3.3.2
  intl: ^0.19.0
  flutter_spinkit: ^5.2.0
  modal_progress_hud_nsn: ^0.4.0
  image_loading_animation: ^0.0.1


dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  
flutter_launcher_icons:  

  android: true
  ios: true
  image_path: "icon/appi.png"
  adaptive_icon_background: "icon/background.png"
  adaptive_icon_foreground: "icon/ic_launcher_adaptive_fore.png"


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: AbhayaLibre
      fonts:
        - asset: fonts/AbhayaLibre-Regular.ttf  
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf    

